// PAN Client Manager — hub-side WebSocket server for pan-client connections.
//
// Clients connect to /ws/client?token=<token>&device_id=<id>
// Each client sends: register, heartbeat, command_result, shell_output, disconnect
// Hub sends: any command from /api/v1/client/command
//
// Usage:
//   import { startClientServer, sendToClient, getConnectedClients } from './client-manager.js';
//   startClientServer(httpServer);  // Call before startTerminalServer

import { WebSocketServer, WebSocket } from 'ws';
import { get, all, run, insert } from './db.js';
import crypto from 'crypto';
import { hostname } from 'os';
import { broadcastNotification } from './terminal-bridge.js';

// In-memory client registry: device_id → { ws, info }
const clients = new Map();

// Rate-limiter for denied devices — prevents rapid reconnect spam in logs
// Maps device_id → { lastLog: timestamp, count: number }
const deniedRateLimit = new Map();
const DENIED_LOG_INTERVAL_MS = 60_000; // only log once per minute per device

// ── Token store (in-memory + DB) ─────────────────────────────────────────────
// Invite tokens are generated by /api/v1/client/invite and consumed on register.
// Stored in settings table as JSON: key='client_invite_tokens' value='[{token,name,expires,used}]'
function getTokens() {
  try {
    const row = get("SELECT value FROM settings WHERE key = 'client_invite_tokens'");
    return row ? JSON.parse(row.value) : [];
  } catch { return []; }
}
function saveTokens(tokens) {
  const existing = get("SELECT id FROM settings WHERE key = 'client_invite_tokens'");
  if (existing) {
    run("UPDATE settings SET value = :v WHERE key = 'client_invite_tokens'", { ':v': JSON.stringify(tokens) });
  } else {
    run("INSERT INTO settings (key, value) VALUES ('client_invite_tokens', :v)", { ':v': JSON.stringify(tokens) });
  }
}

export function createInviteToken(name = 'new-device', ttlMs = 24 * 60 * 60 * 1000) {
  const token = 'pan-' + crypto.randomBytes(16).toString('hex');
  const now = Date.now();
  // Prune expired + used tokens on every creation to prevent pile-up
  const tokens = getTokens().filter(t => !t.used && t.expires > now);
  tokens.push({ token, name, created: now, expires: now + ttlMs, used: false });
  saveTokens(tokens);
  return token;
}

function validateToken(token) {
  const tokens = getTokens();
  const entry = tokens.find(t => t.token === token && !t.used && t.expires > Date.now());
  return !!entry;
}

// Dev mode: allow any token starting with 'dev-'
// 'local' sentinel: connections from the same LAN/Tailscale network discovered
// via UDP broadcast or Tailscale peer scan — no invite needed, but still goes
// through the pending-approval gate so the hub owner must approve them.
function isTokenValid(token) {
  if (!token) return false;
  if (token === 'local') return true;        // local network discovery bypass
  if (token.startsWith('dev-')) return true; // dev bypass
  return validateToken(token);
}

// Exported so install route can check tokens without the dev bypass
export function checkInviteToken(token) {
  if (!token) return false;
  if (token.startsWith('dev-')) return true;
  return validateToken(token);
}

// ── DB migration — runs at module load so routes work before startClientServer ─
(function runMigrations() {
  const migrations = [
    "ALTER TABLE devices ADD COLUMN client_version TEXT",
    "ALTER TABLE devices ADD COLUMN online INTEGER DEFAULT 0",
    // trusted: NULL = never seen as pan-client, 0 = pending approval, 1 = approved, -1 = denied
    "ALTER TABLE devices ADD COLUMN trusted INTEGER DEFAULT NULL",
    `CREATE TABLE IF NOT EXISTS smart_devices (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT,
      type TEXT,
      protocol TEXT,
      address TEXT,
      room TEXT,
      state TEXT,
      discovered_by TEXT,
      last_seen INTEGER,
      org_id TEXT
    )`,
    `CREATE TABLE IF NOT EXISTS client_command_queue (
      id TEXT PRIMARY KEY,
      device_id TEXT NOT NULL,
      type TEXT NOT NULL,
      params TEXT NOT NULL DEFAULT '{}',
      queued_at INTEGER NOT NULL,
      picked_up_at INTEGER,
      result TEXT,
      error TEXT,
      completed_at INTEGER
    )`,
    `CREATE INDEX IF NOT EXISTS idx_ccq_device_pending ON client_command_queue(device_id, picked_up_at)`,
    "ALTER TABLE devices ADD COLUMN reported_services TEXT",
    "ALTER TABLE devices ADD COLUMN tailscale_ip TEXT",
    // #497: how this device's pan-client is launched at startup.
    // service_state:   'system'  = OS service, runs at boot (no login required)
    //                  'user'    = user-session service, runs only after login
    //                  'manual'  = started by hand, won't survive reboot
    //                  'none'    = never registered
    // service_manager: 'nssm' | 'sc' | 'schtasks' | 'launchd-daemon' | 'launchd-agent'
    //                | 'systemd-system' | 'systemd-user' | null
    "ALTER TABLE devices ADD COLUMN service_state TEXT",
    "ALTER TABLE devices ADD COLUMN service_manager TEXT",
    "ALTER TABLE devices ADD COLUMN service_installed_at TEXT",
    `CREATE TABLE IF NOT EXISTS device_audit_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      created_at TEXT DEFAULT (datetime('now','localtime')),
      action TEXT NOT NULL,
      hostname TEXT,
      caller_ip TEXT,
      endpoint TEXT,
      notes TEXT
    )`,
  ];
  for (const sql of migrations) {
    try { run(sql); } catch {} // Ignore duplicate column errors
  }
})();

// ── Device upsert ─────────────────────────────────────────────────────────────
// Returns current trusted value for a device (null if not found)
function getDeviceTrust(device_id) {
  const row = get("SELECT trusted FROM devices WHERE hostname = :h", { ':h': device_id });
  return row ? row.trusted : null;
}

function upsertDevice({ device_id, name, platform, capabilities, version, pending = false, tailscale_ip = null,
                        service_state = null, service_manager = null }) {
  const existing = get("SELECT id, trusted FROM devices WHERE hostname = :h", { ':h': device_id });
  if (existing) {
    // Never downgrade trust — if already approved (1) keep it; only set pending (0) on first-ever pan-client registration
    const newTrust = existing.trusted !== null ? existing.trusted : (pending ? 0 : 1);
    // Don't let the client registration overwrite a human-set name (name column is set by the user via the dashboard).
    // Only set the name if there isn't one already, or if the existing name IS the device_id (never manually renamed).
    const existingRow = get("SELECT name FROM devices WHERE hostname = :h", { ':h': device_id });
    const keepName = existingRow?.name && existingRow.name !== device_id;
    const tsIpClause = tailscale_ip ? ', tailscale_ip = :ts_ip' : '';
    // #497: service_state/manager — COALESCE keeps prior value if client didn't report this round
    run(`UPDATE devices SET ${keepName ? '' : 'name = :n,'} capabilities = :c, client_version = :v, online = 1, trusted = :t${tsIpClause},
         service_state = COALESCE(:ss, service_state),
         service_manager = COALESCE(:sm, service_manager),
         service_installed_at = COALESCE(service_installed_at,
           CASE WHEN :ss IN ('system','user') THEN datetime('now','localtime') ELSE NULL END),
         last_seen = datetime('now','localtime') WHERE hostname = :h`,
      { ':n': name, ':c': JSON.stringify(capabilities || []), ':v': version || null, ':t': newTrust, ':h': device_id,
        ':ss': service_state, ':sm': service_manager, ...(tailscale_ip ? { ':ts_ip': tailscale_ip } : {}) });
  } else {
    run(`INSERT INTO devices (hostname, name, device_type, capabilities, client_version, online, trusted, tailscale_ip,
                              service_state, service_manager, service_installed_at)
         VALUES (:h, :n, 'pc', :c, :v, 1, :t, :ts_ip, :ss, :sm,
                 CASE WHEN :ss IN ('system','user') THEN datetime('now','localtime') ELSE NULL END)`,
      { ':h': device_id, ':n': name, ':c': JSON.stringify(capabilities || []), ':v': version || null, ':t': pending ? 0 : 1,
        ':ts_ip': tailscale_ip, ':ss': service_state, ':sm': service_manager });
  }
}

/**
 * Look up a device by its Tailscale IP (100.x.x.x).
 * Returns the device row or null if not found.
 */
export function getDeviceByTailscaleIp(ip) {
  return get("SELECT * FROM devices WHERE tailscale_ip = :ip", { ':ip': ip }) || null;
}

export function approveDevice(device_id) {
  run("UPDATE devices SET trusted = 1 WHERE hostname = :h", { ':h': device_id });
  const entry = clients.get(device_id);
  if (entry) {
    entry.trusted = true;
    entry.ws.send(JSON.stringify({ type: 'approved', device_id, ok: true }));
  }
  console.log(`[PAN Clients] Approved: ${device_id}`);
}

export function denyDevice(device_id, callerIp = null) {
  run("UPDATE devices SET trusted = -1, online = 0 WHERE hostname = :h", { ':h': device_id });
  try {
    run(`INSERT INTO device_audit_log (action, hostname, caller_ip, endpoint, notes)
         VALUES ('denied', :h, :ip, 'client-manager/denyDevice', 'Device denied by administrator')`,
      { ':h': device_id, ':ip': callerIp || 'internal' });
  } catch {}
  const entry = clients.get(device_id);
  if (entry) {
    entry.ws.send(JSON.stringify({ type: 'denied', device_id, reason: 'Access denied by administrator' }));
    setTimeout(() => { try { entry.ws.close(); } catch {} }, 500);
    clients.delete(device_id);
  }
  console.log(`[PAN Clients] Denied: ${device_id}`);
}

function setDeviceOnline(device_id, online) {
  run("UPDATE devices SET online = :o, last_seen = datetime('now','localtime') WHERE hostname = :h",
    { ':o': online ? 1 : 0, ':h': device_id });
}

// ── WebSocket server ──────────────────────────────────────────────────────────
let wss = null;

export function startClientServer(httpServer) {
  // Mark all devices offline — they'll reconnect if live.
  // Without this, ungraceful disconnects leave online=1 forever.
  // Exclude the hub itself — it runs the heartbeat interval, not WS registration.
  //
  // IMPORTANT: Defer by 3s to avoid a race condition during Carrier restarts.
  // SuperCarrier proxies existing pan-client connections; the new Carrier sends close(1001)
  // which triggers pan-client to reconnect and re-register. That round-trip takes ~500-1500ms.
  // Running the UPDATE immediately marks them offline before they can re-register.
  const hub = hostname();
  setTimeout(() => {
    run("UPDATE devices SET online = 0 WHERE online = 1 AND hostname != :h", { ':h': hub });
  }, 3000);

  wss = new WebSocketServer({ noServer: true });

  // Register our upgrade path. terminal.js's upgrade handler rejects unknown paths,
  // so we register on the same httpServer BEFORE terminal.js to intercept /ws/client.
  httpServer.on('upgrade', (request, socket, head) => {
    const pathname = new URL(request.url, 'http://localhost').pathname;
    if (pathname !== '/ws/client') return; // Let terminal.js handle everything else

    const params = new URL(request.url, 'http://localhost').searchParams;
    const token = params.get('token');
    const deviceId = params.get('device_id');

    // Localhost connections (hub machine itself) always allowed — no invite token needed.
    const remoteIp = request.socket.remoteAddress || '';
    const isLocalhost = remoteIp === '127.0.0.1' || remoteIp === '::1' || remoteIp === '::ffff:127.0.0.1';
    // Already-approved devices can reconnect even if their invite token has expired.
    const deviceTrust = deviceId ? getDeviceTrust(deviceId) : null;
    const isApproved = deviceTrust === 1;
    if (!isLocalhost && !isApproved && !isTokenValid(token)) {
      socket.write('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');
      socket.destroy();
      console.warn(`[PAN Clients] Rejected connection: invalid token (device=${deviceId})`);
      return;
    }

    // Capture Tailscale IP if the connection comes from the 100.x.x.x range
    const tailscaleIp = remoteIp.startsWith('100.') ? remoteIp : null;

    wss.handleUpgrade(request, socket, head, (ws) => {
      ws._panDeviceId = deviceId;
      ws._panTailscaleIp = tailscaleIp;
      wss.emit('connection', ws, request);
    });
  });

  wss.on('connection', (ws, req) => {
    const params = new URL(req.url, 'http://localhost').searchParams;
    const deviceId = params.get('device_id') || ws._panDeviceId || 'unknown';
    const token = params.get('token') || '';
    const isDevToken = token.startsWith('dev-');
    ws._panToken = token;
    ws._panDevMode = isDevToken;
    console.log(`[PAN Clients] New connection: ${deviceId}`);

    ws.on('message', (data) => {
      let msg;
      try { msg = JSON.parse(data); } catch { return; }
      handleClientMessage(ws, deviceId, msg);
    });

    ws.on('close', () => {
      console.log(`[PAN Clients] Disconnected: ${deviceId}`);
      clients.delete(deviceId);
      setDeviceOnline(deviceId, false);
      broadcastNotification('widget_update', { widget: 'devices' });
    });

    ws.on('error', (err) => {
      console.error(`[PAN Clients] WS error (${deviceId}):`, err.message);
    });

    ws.on('pong', () => {
      const entry = clients.get(deviceId);
      if (entry) entry.lastPong = Date.now();
    });
  });

  // Periodic ping to detect dead connections
  setInterval(() => {
    for (const [id, entry] of clients) {
      if (entry.ws.readyState === WebSocket.OPEN) {
        entry.ws.ping();
      } else {
        clients.delete(id);
        setDeviceOnline(id, false);
      }
    }
  }, 30_000);

  console.log('[PAN Clients] Client WebSocket server ready on /ws/client');
  return wss;
}

// ── Message handlers ──────────────────────────────────────────────────────────
function handleClientMessage(ws, deviceId, msg) {
  switch (msg.type) {
    case 'register':
      handleRegister(ws, deviceId, msg);
      break;

    case 'heartbeat':
      handleHeartbeat(deviceId, msg);
      break;

    case 'command_result':
      handleCommandResult(deviceId, msg);
      break;

    case 'shell_output':
      handleShellOutput(deviceId, msg);
      break;

    case 'disconnect':
      console.log(`[PAN Clients] Clean disconnect: ${deviceId} (${msg.reason})`);
      clients.delete(deviceId);
      setDeviceOnline(deviceId, false);
      break;

    default:
      console.log(`[PAN Clients] Unknown message type: ${msg.type} from ${deviceId}`);
  }
}

function handleRegister(ws, deviceId, msg) {
  // Dev tokens and previously-approved devices skip the approval gate
  const isDevToken = ws._panDevMode;
  const existingTrust = getDeviceTrust(deviceId);
  const alreadyApproved = existingTrust === 1;
  const wasDenied = existingTrust === -1;

  if (wasDenied) {
    ws.send(JSON.stringify({ type: 'denied', device_id: deviceId, reason: 'This device was previously denied by the administrator' }));
    // Close with a longer delay (3s) to slow down rapid reconnect loops
    setTimeout(() => { try { ws.close(); } catch {} }, 3000);
    // Rate-limit the log — only warn once per minute per device to avoid spam
    const now = Date.now();
    const rl = deniedRateLimit.get(deviceId) || { lastLog: 0, count: 0 };
    rl.count++;
    if (now - rl.lastLog >= DENIED_LOG_INTERVAL_MS) {
      const suffix = rl.count > 1 ? ` (${rl.count}x in last minute)` : '';
      console.warn(`[PAN Clients] Blocked previously-denied device: ${deviceId}${suffix}`);
      rl.lastLog = now;
      rl.count = 0;
    }
    deniedRateLimit.set(deviceId, rl);
    return;
  }

  const pending = !isDevToken && !alreadyApproved;

  clients.set(deviceId, {
    ws,
    device_id: deviceId,
    name: msg.name || deviceId,
    platform: msg.platform,
    version: msg.version,
    capabilities: msg.capabilities || [],
    connected_at: Date.now(),
    lastPong: Date.now(),
    trusted: !pending,
  });
  upsertDevice({
    device_id: deviceId,
    name: msg.name || deviceId,
    platform: msg.platform,
    capabilities: msg.capabilities,
    version: msg.version,
    pending,
    tailscale_ip: ws._panTailscaleIp || null,
    service_state: msg.service_state || null,
    service_manager: msg.service_manager || null,
  });

  if (pending) {
    ws.send(JSON.stringify({ type: 'pending_approval', device_id: deviceId, message: 'Waiting for administrator approval' }));
    console.log(`[PAN Clients] Pending approval: ${msg.name || deviceId} (${msg.platform})`);
    // Notify the dashboard so the hub owner sees an approve/deny prompt immediately
    broadcastNotification('device_pending', {
      device_id: deviceId,
      name: msg.name || deviceId,
      platform: msg.platform || 'unknown',
      message: `New device wants to join: ${msg.name || deviceId} (${msg.platform || 'unknown'})`,
    }).catch(() => {});
  } else {
    ws.send(JSON.stringify({ type: 'registered', device_id: deviceId, ok: true }));
    console.log(`[PAN Clients] Registered: ${msg.name || deviceId} (${msg.platform}, v${msg.version})`);
    broadcastNotification('widget_update', { widget: 'devices' }).catch(() => {});
  }
}

function handleHeartbeat(deviceId, msg) {
  const entry = clients.get(deviceId);
  if (entry) {
    entry.last_heartbeat = msg.timestamp;
    entry.mem_free_mb = msg.mem_free_mb;
    if (msg.services) entry.reported_services = msg.services;
    if (msg.service_state) entry.service_state = msg.service_state;
    if (msg.service_manager) entry.service_manager = msg.service_manager;
  }
  setDeviceOnline(deviceId, true);
  if (msg.services) {
    run("UPDATE devices SET reported_services = :s WHERE hostname = :h",
      { ':s': JSON.stringify(msg.services), ':h': deviceId });
  }
  // #497: refresh service_state on every WS heartbeat. The CASE in the
  // service_installed_at clause stamps first-observation only.
  if (msg.service_state !== undefined || msg.service_manager !== undefined) {
    run(`UPDATE devices SET
           service_state = COALESCE(:ss, service_state),
           service_manager = COALESCE(:sm, service_manager),
           service_installed_at = COALESCE(service_installed_at,
             CASE WHEN :ss IN ('system','user') THEN datetime('now','localtime') ELSE NULL END)
         WHERE hostname = :h`,
      { ':h': deviceId, ':ss': msg.service_state ?? null, ':sm': msg.service_manager ?? null });
  }
}

// Pending command replies: commandId → { resolve, reject, timer }
const pendingCommands = new Map();

// HTTP command queue: deviceId → [{ id, type, params }]
// Used when device connects via HTTP polling (Cloudflare tunnel) instead of WebSocket
const httpCommandQueue = new Map();
// Long-poll waiters: deviceId → { res, timer }
const httpPollWaiters = new Map();

/** Called by GET /api/v1/client/poll — holds connection until command or timeout */
export function registerHttpPollWaiter(deviceId, res, timeoutMs = 25_000) {
  const queue = httpCommandQueue.get(deviceId);
  if (queue?.length) {
    const cmd = queue.shift();
    return res.json({ ok: true, command: cmd });
  }
  const existing = httpPollWaiters.get(deviceId);
  if (existing) { clearTimeout(existing.timer); try { existing.res.json({ ok: true, command: null }); } catch {} }
  const timer = setTimeout(() => {
    httpPollWaiters.delete(deviceId);
    try { res.json({ ok: true, command: null }); } catch {}
  }, timeoutMs);
  httpPollWaiters.set(deviceId, { res, timer });
}

/** Called by POST /api/v1/client/result — resolves the sendToClient promise */
export function resolveHttpCommand(cmdId, result, error) {
  const pending = pendingCommands.get(cmdId);
  if (pending) {
    clearTimeout(pending.timer);
    pendingCommands.delete(cmdId);
    if (error) pending.reject(new Error(error));
    else pending.resolve(result);
  }
}

function handleCommandResult(deviceId, msg) {
  const pending = pendingCommands.get(msg.id);
  if (pending) {
    clearTimeout(pending.timer);
    pendingCommands.delete(msg.id);
    if (msg.ok) pending.resolve(msg.result);
    else pending.reject(new Error(msg.error || 'Command failed'));
  }
}

// Shell output streaming: commandId → callback
const shellOutputHandlers = new Map();

export function onShellOutput(commandId, fn) {
  shellOutputHandlers.set(commandId, fn);
}

function handleShellOutput(deviceId, msg) {
  const handler = shellOutputHandlers.get(msg.id);
  if (handler) handler(msg.chunk, msg.stream || 'stdout');
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Send a command to a connected client. Returns a promise that resolves with the result.
 * @param {string} deviceId - Target device hostname
 * @param {string} type - Command type (e.g. 'shell_exec', 'notification')
 * @param {object} params - Command parameters
 * @param {number} timeoutMs - Timeout in ms (default 30s)
 */
export function sendToClient(deviceId, type, params = {}, timeoutMs = 30_000) {
  const entry = clients.get(deviceId);
  const wsOk = entry && entry.ws.readyState === WebSocket.OPEN;
  const httpOk = httpPollWaiters.has(deviceId) || httpCommandQueue.has(deviceId);

  if (!wsOk && !httpOk) {
    return Promise.reject(new Error(`Client '${deviceId}' not connected`));
  }
  if (entry && !entry.trusted) {
    return Promise.reject(new Error(`Client '${deviceId}' is pending approval`));
  }

  const id = crypto.randomUUID();
  const cmd = { id, type, ...params };

  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      pendingCommands.delete(id);
      reject(new Error(`Command timeout: ${type} → ${deviceId}`));
    }, timeoutMs);
    pendingCommands.set(id, { resolve, reject, timer });

    if (wsOk) {
      entry.ws.send(JSON.stringify(cmd));
    } else {
      // HTTP queue fallback — client is polling via GET /api/v1/client/poll
      if (!httpCommandQueue.has(deviceId)) httpCommandQueue.set(deviceId, []);
      const waiter = httpPollWaiters.get(deviceId);
      if (waiter) {
        // Long-poll connection waiting — deliver immediately
        clearTimeout(waiter.timer);
        httpPollWaiters.delete(deviceId);
        try { waiter.res.json({ ok: true, command: cmd }); } catch {}
      } else {
        httpCommandQueue.get(deviceId).push(cmd);
      }
    }
  });
}

/**
 * Fire-and-forget command (no reply waiting).
 */
export function fireToClient(deviceId, type, params = {}) {
  const entry = clients.get(deviceId);
  if (!entry || entry.ws.readyState !== WebSocket.OPEN || !entry.trusted) return false;
  entry.ws.send(JSON.stringify({ type, ...params }));
  return true;
}

/**
 * List all currently connected clients.
 */
export function getConnectedClients() {
  const result = [];
  for (const [id, entry] of clients) {
    result.push({
      device_id: id,
      name: entry.name,
      platform: entry.platform,
      version: entry.version,
      capabilities: entry.capabilities,
      connected_at: entry.connected_at,
      last_heartbeat: entry.last_heartbeat,
      mem_free_mb: entry.mem_free_mb,
      online: entry.ws.readyState === WebSocket.OPEN,
      trusted: entry.trusted,         // false = pending approval
    });
  }
  return result;
}

/**
 * Check if a specific client is connected.
 */
export function isClientConnected(deviceId) {
  const entry = clients.get(deviceId);
  return !!(entry && entry.ws.readyState === WebSocket.OPEN);
}
